language: cpp

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      env:
        - BUILD_TYPE="Debug
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: linux
      sudo: false
      dist: trusty
      env:
        - BUILD_TYPE="Release
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: linux
      sudo: false
      dist: trusty
      env:
        - BUILD_TYPE="Debug
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      compiler: xcode6.4
      env: BUILD_TYPE="Debug"

    - os: osx
      compiler: xcode8
      env: BUILD_TYPE="Release"

addons:
  apt:
    packages:
      - cmake
      - g++-5
      - g++-9
      - libfreetype6-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxcursor-dev
      - mesa-common-dev
      - libasound2-dev
      - freeglut3-dev
      - libxcomposite-dev
    sources:
      - ubuntu-toolchain-r-test

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make -j 2

# Disable notifications
notifications:
  email: false
