language: cpp
compiler: g++

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc
      env: BUILD_TYPE="Debug" CXX="g++-5" CC="g++-5"

    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc
      env: BUILD_TYPE="Release" CXX="g++-5" CC="g++-5"

    - os: osx
      compiler: xcode6.4
      env: BUILD_TYPE="Debug"

    - os: osx
      compiler: xcode8
      env: BUILD_TYPE="Release"

addons:
  apt:
    packages:
      - cmake
      - g++-5
      - libfreetype6-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxcursor-dev
      - mesa-common-dev
      - libasound2-dev
      - freeglut3-dev
      - libxcomposite-dev
    sources:
      - ubuntu-toolchain-r-test

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make -j 2

# Disable notifications
notifications:
  email: false
