version: '{build}'

image: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Debug

    #- GENERATOR: "Visual Studio 14 2015"
    #  CONFIG: Debug

build_script:
  - git submodule update --init --recursive
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"
